### ISSUE TITLE
Run the workflow locally

### ISSUE THREAD

**Issue by Poccia** [franciscozorrilla/metaGEM#108]
**I just want to know if it is possible to run the workflow locally on my computer.** I've setup the workflow e just then noticed that it is designed for clusters, but I'm working on a computer that can handle the job.

**Comment by franciscozorrilla** [comment]
Hey, yes its possible with the `--local` flag, just might take some extra setup and tweaking to get things going. There some more details in this thread/comment but please let me know if you run into any issues/questions.
