### ISSUE TITLE
How could I get full name of compound in SMETANA result?

### ISSUE THREAD

**Issue by xhxlilium** [franciscozorrilla/metaGEM#109]
![image](https://user-images.githubusercontent.com/44562411/187874603-f4e28113-74ae-4407-8b92-c7464e1e580c.png)
I saw compounds in result of SMETANA  in tutorial was like above, but in data visualization it changes into full name. How could I get this?
![image](https://user-images.githubusercontent.com/44562411/187874874-62bcef0a-22ab-4c2c-95a2-8340065e7aa6.png)

**Comment by franciscozorrilla** [comment]
You may use the metabolites file found in the[ bigg database](http://bigg.ucsd.edu/data_access).
Also have a look at the SymbNET repo, in particular [this notebook](https://github.com/franciscozorrilla/SymbNET/blob/main/scripts/4.plot_smetana_detailed_interactions.md), where I use the [metabolite classes file](https://github.com/franciscozorrilla/SymbNET/blob/main/data/bigg_classes.txt) instead. 

More specifically, I use the left_join() tidyverse function to join the SMETANA and metabolite names as shown in this [code snippet](https://github.com/franciscozorrilla/SymbNET/blob/main/scripts/4.plot_smetana_detailed_interactions.md#-data):

```
# Load in some metabolite metadata
smetana_met <- read.delim("../data/bigg_classes.txt")
smet_all <- left_join(smet_all,smetana_met,by="compound")%>%
     mutate(name=as.factor(name))%>%
     mutate(super_class=as.factor(super_class))%>%
     mutate(class=as.factor(class))%>%
     mutate(sub_class=as.factor(sub_class))%>%
     drop_na()%>%
     unique()
```

**Comment by xhxlilium** [comment]
I solved this problem through your method. Thank you very much!
