### ISSUE TITLE
Having difficulties understanding SMETANA codes

### ISSUE THREAD

**Issue by White-Shinobi** [franciscozorrilla/metaGEM#113]
Hi Francisco,

I tired to check the SMETANA codes to understand the software's logics. And I found the smetana.py are using functions from a package called **reframed** from Daniel Machado.
But I can not find resources to indicate the functions in Reframed. May I ask do you know where I can learn about the functions in reframed or some explanations for SMETANA codes?

Best, 
Yue

**Comment by franciscozorrilla** [comment]
Hi Yue,

You may find the SMETANA GitHub repo and associated code [here](https://github.com/cdanielmachado/smetana). Please also have a look at the accompanying [paper](https://www.pnas.org/doi/10.1073/pnas.1421834112). [Reframed](https://github.com/cdanielmachado/reframed) is the metabolic modelling package that Daniel developed, and is used by a number of his tools.

Hope this helps!
Best,
Francisco
