### ISSUE TITLE
Error parsing number of cores (--cores, -c, -j): must be integer, empty, or 'all'.

### ISSUE THREAD

**Issue by LiZhihua1982** [franciscozorrilla/metaGEM#117]
Dear Dr.Franciscozorrilla,
         when I "bash metaGEM.sh -t crossMapSeries -j 2 --nCores 24 -m 120 -h 24"          it reported  error "error parsing number of cores (--cores, -c, -j): must be integer, empty, or 'all'." 
(base) lizhihua@lizhihua-T640:/media/lizhihua/software/metaGEM$ bash metaGEM.sh -t crossMapSeries -j 2 --nCores 24 -m 120 -h 24

=================================================================================================================================
Developed by: Francisco Zorrilla, Kiran R. Patil, and Aleksej Zelezniak___________________________________________________________
Publication: doi.org/10.1101/2020.12.31.424982___________________________/\\\\\\\\\\\\___/\\\\\\\\\\\\\\\___/\\\\____________/\\\\_        
________________________________________________________________________/\\\//////////___\/\\\///////////___\/\\\\\\________/\\\\\\_       
____________________________________________/\\\________________________/\\\______________\/\\\______________\/\\\//\\\____/\\\//\\\_      
_______/\\\\\__/\\\\\________/\\\\\\\\____/\\\\\\\\\\\___/\\\\\\\\\_____\/\\\____/\\\\\\\__\/\\\\\\\\\\\______\/\\\\///\\\/\\\/_\/\\\_     
______/\\\///\\\\\///\\\____/\\\/////\\\__\////\\\////___\////////\\\____\/\\\___\/////\\\__\/\\\///////_______\/\\\__\///\\\/___\/\\\_    
______\/\\\_\//\\\__\/\\\___/\\\\\\\\\\\______\/\\\_________/\\\\\\\\\\___\/\\\_______\/\\\__\/\\\______________\/\\\____\///_____\/\\\_   
_______\/\\\__\/\\\__\/\\\__\//\\///////_______\/\\\_/\\____/\\\/////\\\___\/\\\_______\/\\\__\/\\\______________\/\\\_____________\/\\\_  
________\/\\\__\/\\\__\/\\\___\//\\\\\\\\\\_____\//\\\\\____\//\\\\\\\\/\\__\//\\\\\\\\\\\\/___\/\\\\\\\\\\\\\\\__\/\\\_____________\/\\\_ 
_________\///___\///___\///_____\//////////_______\/////______\////////\//____\////////////_____\///////////////___\///______________\///__
=============================================================================================================================================
A Snakemake-based pipeline desinged to predict metabolic interactions directly from metagenomics data using high performance computer clusters
===============================================================================================================================================

Setting current directory to root in config.yaml file ... 

Parsing Snakefile to target rule: crossMapSeries ... 
Number of jobs to be sumitted to cluster: 2 ... 
Parsing cluster_config.json to match requested number of cores: 24 ... 
Parsing cluster_config.json to match requested time (hours): 24 ... 
Parsing cluster_config.json to match requested memory: 120 ... 
 
Do you wish to continue with these parameters? (y/n)y
Proceeding with crossMapSeries job(s) ... 

Please verify parameters set in the config.yaml file: 

path:
    root: /media/lizhihua/software/metaGEM
    scratch: /media/lizhihua/software/metaGEM_tem
folder:
    data: dataset
    logs: logs
    assemblies: assemblies
    scripts: scripts
    crossMap: crossMap 
    concoct: concoct
    maxbin: maxbin
    metabat: metabat
    refined: refined_bins
    reassembled: reassembled_bins
    classification: GTDBTk
    abundance: abundance
    GRiD: GRiD
    GEMs: GEMs
    SMETANA: SMETANA
    memote: memote
    qfiltered: qfiltered
    stats: stats
    proteinBins: protein_bins
    dnaBins: dna_bins
    pangenome: pangenome
    kallisto: kallisto
    kallistoIndex: kallistoIndex
    benchmarks: benchmarks
    prodigal: prodigal
    blastp: blastp
    blastp_db: 
scripts:
    kallisto2concoct: kallisto2concoct.py
    prepRoary: prepareRoaryInput.R
    binFilter: binFilter.py
    qfilterVis: qfilterVis.R
    assemblyVis: assemblyVis.R
    binningVis: binningVis.R
    modelVis: modelVis.R
    compositionVis: compositionVis.R
    taxonomyVis: taxonomyVis.R
    carveme: media_db.tsv
    toy: download_toydata.txt
    GTDBtkVis: 
cores:
    fastp: 4
    megahit: 48
    crossMap: 48
    concoct: 48
    metabat: 48
    maxbin: 48
    refine: 48
    reassemble: 48
    classify: 2
    gtdbtk: 48
    abundance: 16
    carveme: 4
    smetana: 12
    memote: 4
    grid: 24
    prokka: 2
    roary: 12
    diamond: 12
params:
    cutfasta: 10000
    assemblyPreset: meta-sensitive
    assemblyMin: 1000
    concoct: 800
    metabatMin: 50000
    seed: 420
    minBin: 1500
    refineMem: 1600
    refineComp: 50
    refineCont: 10
    reassembleMem: 1600
    reassembleComp: 50
    reassembleCont: 10
    carveMedia: M8
    smetanaMedia: M1,M2,M3,M4,M5,M7,M8,M9,M10,M11,M13,M14,M15A,M15B,M16
    smetanaSolver: CPLEX
    roaryI: 90
    roaryCD: 90
envs:
    metagem: /media/lizhihua/software/metaGEM/envs/metagem
    metawrap: /media/lizhihua/software/metaGEM/envs/metawrap
    prokkaroary: /media/lizhihua/software/metaGEM/envs/prokkaroary

Please pay close attention to make sure that your paths are properly configured!
Do you wish to proceed with this config.yaml file? (y/n)y
 
Please verify parameters set in the cluster_config.json file: 

{
"__default__" : {
        "account" : "LZLJ",
        "time" : "0-24:00:00",
        "n" : 24,
        "tasks" : 1,
        "mem" : 120G,
        "name"      : "DL.{rule}",
        "output"    : "logs/{wildcards}.%N.{rule}.out.log",
},

 
Do you wish to proceed with this cluster_config.json file? (y/n)y
 
Unlocking snakemake ... 
/home/lizhihua/miniconda3/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.11) or chardet (5.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Unlocking working directory.

Dry-running snakemake jobs ... 
Error parsing number of cores (--cores, -c, -j): must be integer, empty, or 'all'.
Do you wish to submit this batch of jobs? (y/n)y
nohup: appending output to 'nohup.out'
(base) lizhihua@lizhihua-T640:/media/lizhihua/software/metaGEM$

**Comment by franciscozorrilla** [comment]
Hi Li,

Please also have a look at other issues before posting a new one, it is very likely that you will find helpful discussion there.
For example, you will find the answer to your problem in this solved issue #103, where another user reported the same error message as you.
You probably are running a newer version of Snakemake, and you will need to downgrade to version 5.10.

Best,
Francisco
