### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by fconstancias** [franciscozorrilla/metaGEM#122]
Dear @franciscozorrilla ,

Thanks for developping those tools and alos the efforts you are putting in educating !

I am trying to install metaGEM on a apple M1 computer and I got the following error:

` mamba create -n metagem -c bioconda metagem`

> Encountered problems while solving:
>   - nothing provides concoct >=1.1.0 needed by metagem-1.0.5-hdfd78af_0

any idea what is wrong here?

Thanks!

**Comment by franciscozorrilla** [comment]
Hello! thanks for the kind words and sorry to hear you are having issues. I believe that configuring your conda channels should fix this issue, could you try running this command before re-running the mamba install command?

```
conda config --add channels conda-forge
```

**Comment by fconstancias** [comment]
Unfortunately, it did not help.

` conda activate base `

` conda config --add channels conda-forge `

`mamba create -n metagem -c bioconda metagem`

> Looking for: ['metagem']
> 
> bioconda/osx-64          Using cache
> bioconda/noarch          Using cache
> conda-forge/osx-64       Using cache
> conda-forge/noarch       Using cache
> pkgs/r/noarch            [====================] (00m:00s) No change
> pkgs/main/noarch         [====================] (00m:00s) No change
> pkgs/r/osx-64            [====================] (00m:00s) No change
> pkgs/main/osx-64         [====================] (00m:00s) No change
> Encountered problems while solving:
>   - nothing provides concoct >=1.1.0 needed by metagem-1.0.5-hdfd78af_0
>

**Comment by fconstancias** [comment]
Good point, thanks!
