### ISSUE TITLE
[Bug]: 'BiGG_gene' is both an index level and a column label, which is ambiguous.

### ISSUE THREAD

**Issue by Baizhou12138** [franciscozorrilla/metaGEM#137]
Hi Professor.
I'm a newbie and I'm trying to construct a community metabolic model using carveme in order to analyze the metabolic characteristics of the community using smetana solver.I already had the data fasta file from the commercial company that handles the annotated data, so I decided to start with step 6 of the workflow.
I am encountering some strange erro's that report errors as follows:
![unnamed](https://github.com/franciscozorrilla/metaGEM/assets/141997418/e0755dee-91f3-4085-8b5b-3586b904243f)
im not sure where the peoblems are and how to fix that.Oh,In addition, I will show you my fasta file format if it will help you to understand.
![unnamed](https://github.com/franciscozorrilla/metaGEM/assets/141997418/7cb3bfb7-996a-4635-8920-8442ac973798)
![unnamed](https://github.com/franciscozorrilla/metaGEM/assets/141997418/e4cfb22c-9779-44da-b0dd-2fe25de4960d)
I have about 9,000 similar files that need to be analyzed at the same time.what should i do?QAQ I would really appreciate it if you could give me a guide.Thanks again.

**Comment by Baizhou12138** [comment]
I'm wondering if I can use my existing annotated fasta file to directly perform the "Reconstruct & evaluate genome-scale metabolic models with CarveMe and memote" and "Species metabolic coupling analysis with SMETANA" in the workflow. Please let me know if my question is not clear enough. i'm really looking forward to your help. thanks again.

**Comment by franciscozorrilla** [comment]
Hey Baizhou, thanks for posting your issue with screenshots and explanations. I believe this is not a big, rather you are providing CarveMe with the incorrect input file. You need to translate to protein and preform open reading frame (ORF) annotation. For reference have a look at the following tutorial https://github.com/franciscozorrilla/EMBOMicroCom/blob/main/exercises/exercise_4.md

**Comment by winnieLu-cup** [comment]
> Hey Baizhou, thanks for posting your issue with screenshots and explanations. I believe that this is not a bug, rather you are providing CarveMe with the incorrect input file. You need to translate the DNA to protein and perform open reading frame (ORF) annotation. For reference have a look at the following tutorial https://github.com/franciscozorrilla/EMBOMicroCom/blob/main/exercises/exercise_4.md

follow the turorial, and mistakes still exist. Is it possible that CarveMe is incompatible with the versions of python, diamond, and solver?
![image](https://github.com/franciscozorrilla/metaGEM/assets/71426525/b8e721e4-f13c-496a-b0bb-b4e6a76e6526)
![image](https://github.com/franciscozorrilla/metaGEM/assets/71426525/72361fc1-3e1a-4c81-9a7a-49a0827aac5c)

**Comment by franciscozorrilla** [comment]
Hi @winnieLu-cup, it looks like your input file is now correct, I am not sure why the error is occuring. It does not seem to be a common issues topic on the CarveMe github repo, it could be buggy behavior related to the recently added SCIP solver, maybe you could try with cplex academic version instead?
