### ISSUE TITLE
[Question]:Why, when I use CarveMe for gap-filling, does it show that my custom medium does not exist in the database?

### ISSUE THREAD

**Issue by microbial-cookie** [franciscozorrilla/metaGEM#145]
Hi developer,

I have been trying to construct microbial genome-level metabolic models using GEM recently. However, I encountered an issue during gap-filling, indicating that my custom medium, which I defined based on the BIGG metabolite database and existing culture medium components, does not exist in the original database. As a result, I am uncertain whether the .xml file I generated during the construction process has been gap-filled according to my custom medium. Below are images of the code and workflow I used. Although I obtained the .xml file, I am unsure if the result is correct and why it is indicating that my medium does not exist in database. Happy new year!!!

Ruiwen

![image](https://github.com/franciscozorrilla/metaGEM/assets/133230591/39042bb0-a1e3-4e54-aa4f-b97a52e4b639)
![image](https://github.com/franciscozorrilla/metaGEM/assets/133230591/6bf6b8b6-e52d-48e6-bef5-50df67058c75)

**Comment by franciscozorrilla** [comment]
Hi @microbial-cookie, the errors are related to the fact that you are using the wrong flags/parameters. More specifically, you are missing the media database flag `--mediadb`, and you are incorrectly using the `--gapfill` flag which should be specifying a media compostion in your database. Please have a look at the help message or look at [this tutorial](https://github.com/franciscozorrilla/SymbNET/blob/main/scripts/1.carve_models.md) for further reference.
