### ISSUE TITLE
[Question]: I meet some errors when I use CarveMe for gap-filling?

### ISSUE THREAD

**Issue by microbial-cookie** [franciscozorrilla/metaGEM#146]
Hi franciscozorrilla,

After I run the gap-filling command using my defined medium, I meet errors, as below:

![image](https://github.com/franciscozorrilla/metaGEM/assets/133230591/4407353b-5d32-4a43-a674-0eb680548f01)

![image](https://github.com/franciscozorrilla/metaGEM/assets/133230591/bee193cc-ba65-4a51-a563-524bf4ffee96)

![image](https://github.com/franciscozorrilla/metaGEM/assets/133230591/25444808-ab3c-4aad-889d-e6ed0d06710a)

Sorry, I don't know what means, how can I do to solve this problem, please help me, thanks so much, Happy new year!!!!

Ruiwen

**Comment by franciscozorrilla** [comment]
The errors are probably related to your incorrectly generated media database file. In the last line, benzoate should not have compartment information. Simply replace `bz_c` with `bz`.

**Comment by microbial-cookie** [comment]
Hi franciscozorrilla,

I would like to ask you, are the two files marked in red below generated from SMETANA results? I used the command smetana *-LB-model.xml -m LB --mediadb media-LB.tsv --detailed --verbose, but similar files did not appear. I wanted to inquire about how you obtained these two files. Thank you very much.

![image](https://github.com/franciscozorrilla/metaGEM/assets/133230591/644c7bb1-0a87-455c-969f-20d567b30d32)

**Comment by franciscozorrilla** [comment]
Hi @microbial-cookie, no those files are not generated by SMETANA. I can see how the commit message could be misleading if one does not understand what the different tools are doing, I must have added many files at once. Those two files are generated based on the GEM output of CarveMe. To understand the usage and output of SMETANA, please read the [documentation](https://smetana.readthedocs.io/en/latest/usage.html) and check out this repo [tutorial](https://github.com/franciscozorrilla/SymbNET/blob/main/scripts/3.run_smetana_detailed_interactions.md). 

Ruiwen, I would like to ask you to please keep the questions organized by topic, this makes it easier for me to reference and for future users to read through similar issues they may have. Your original post/issue was about CarveMe, and now you are asking a question about SMETANA, in such cases please open a new issue. Furthermore, your question is related to the [mi_cheese](https://github.com/Chrats-Melkonian/mi_cheese) repo, so please open an issue in that repo if you have further questions.

Best,
Francisco
