### ISSUE TITLE
[Question]: How to use the GEM output of CarveMe to generate these two files?

### ISSUE THREAD

**Issue by microbial-cookie** [franciscozorrilla/metaGEM#149]
Hi franciscozorrilla,

I used the command like this (for i in *.faa do carve $i --fbc2  --gapfill LB  --mediadb media-LB.tsv  -o $i-LB-model.xml
done) to generate the GEM files. But I didn't find these two files. Could you tell me about the command to generate these files? I think it is important for my following results. Thanks a lot!

![image](https://github.com/franciscozorrilla/metaGEM/assets/133230591/083698ea-4b16-48c6-8f86-1df22b56cfa2)

**Comment by franciscozorrilla** [comment]
Please read the CarveMe [documentation](https://carveme.readthedocs.io/en/latest/usage.html) to understand the expected output, CarveMe will not produce those files for you, but you can generate them based on the GEM output + cobrapy/reframed + some scripting. If you have questions about the cheese study data/code, please raise an issue in that repository and I will be happy to help.
