### ISSUE TITLE
Rule assemblyVis has commented out two relevant lines

### ISSUE THREAD

**Issue by matrs** [franciscozorrilla/metaGEM#34]
https://github.com/franciscozorrilla/metaGEM/blob/ae3e5e3c9917fc262b109e219b98ccc6e6340223/Snakefile#L327
https://github.com/franciscozorrilla/metaGEM/blob/ae3e5e3c9917fc262b109e219b98ccc6e6340223/Snakefile#L330

Hey, this two lines and the remove of the redundant plot are commented out, so the task fails

**Comment by franciscozorrilla** [comment]
Hi, thanks for pointing that out! I must have been testing/prototyping and forgot to uncomment those lines, will fix ASAP.
Also, the visualization rules R scripts are pretty basic although still useful for quick visualization, I will update them in a coming patch to make nicer/more custom plots.
