### ISSUE TITLE
Someone can provide a virtual disk or something to run data directly? 

### ISSUE THREAD

**Issue by kingtom2016** [franciscozorrilla/metaGEM#47]
Someone can provide a virtual disk or something to run data directly? It is too hard for me to set up the metaGEM. I encounter a lot of problems in my ubuntu virtualbox and WSL2. I've given up seting up metaGEM enivronment. :(

**Comment by franciscozorrilla** [comment]
Hi Jint,

Sorry to hear you are having trouble with the installation, I am happy to help you with your setup. 

Could you clarify if you are trying to set up metaGEM on your local machine or on a high performance computer cluster? Are you following the manual installation or using the automated `env_setup.sh` script? What errors are you encountering?

In case you haven't seen it already, please take a look at the installation [documentation](https://github.com/franciscozorrilla/metaGEM/wiki) or the google colab [notebook](https://colab.research.google.com/drive/1I1S8AoGuJ9Oc2292vqAGTDmZcbnolbuj#scrollTo=IdqjsG1nvQVV). Specifically in subsection 2 of the notebook you can see how to install metaGEM on a virtual machine:

```
# clone metaGEM repo
git clone https://github.com/franciscozorrilla/metaGEM.git

# move into metaGEM folder
cd metaGEM

# create mamba env for faster installation
conda create --prefix ./envs/mamba mamba -c conda-forge

# activate mamba env
source activate envs/mamba

# set up metagem
mamba env create --prefix ./envs/metagem -f envs/metaGEM_env.yml
```

Please let me know if this installation procedure works for you. 

Best,
Francisco
