### ISSUE TITLE
'compositionVis' , 'abundanceVis' and 'taxonomyVis' rule errors

### ISSUE THREAD

**Issue by shreyanshumale** [franciscozorrilla/metaGEM#48]
Hello Francisco!

1. I was following the unseenbio examples, but when I run: _bash metaGEM.sh -t compositionVis_ the terminal throws an error that there is no task under that name. When I check the Snakefile, I do find a _compositionVis_ rule. 
2. And when I run  _bash metaGEM.sh -t taxonomyVis_. I get this error: _No rule to produce taxonomyVis_
3. Same error as 2 again when I run bash command for _abundanceVis_

Can you please tell me why this happens?

Thanks,
Shreyansh

**Comment by franciscozorrilla** [comment]
Hi Shreyan,

Ah yes sorry about that, many of the visualization rules are still being developed and I need to add them to the `metaGEM.sh` parser. Also the plotting scripts are generally very basic at the moment and are mostly meant for sanity checking. Let me know if there are any particular result visualizations that you would find useful. In any case, I have added this item to the to-do list for the next release of `metaGEM v1.1.0`.

Best wishes,
Francisco

**Comment by franciscozorrilla** [comment]
fixed in issue #63
