### ISSUE TITLE
 sbatch: not found Error submitting jobscript (exit code 127):

### ISSUE THREAD

**Issue by kingtom2016** [franciscozorrilla/metaGEM#49]
I primarily install the metaGEM and run with toy dataset. And I got no error (red words) in bash, but a error in nohup.out. 
Is that due to the configuration and software about cluster?
I run it on Ubuntu20.04 in virtualbox in my PC (40G RAM)

####################
Here is the error recorded in nohup.out.

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 2
Job counts:
	count	jobs
	1	all
	2	qfilter
	3
Select jobs to execute...

[Sun May 30 10:25:13 2021]
rule qfilter:
    input: /media/sf_stone_meta/software/metaGEM/dataset/sample1/sample1_R1.fastq.gz, /media/sf_stone_meta/software/metaGEM/dataset/sample1/sample1_R2.fastq.gz
    output: /media/sf_stone_meta/software/metaGEM/qfiltered/sample1/sample1_R1.fastq.gz, /media/sf_stone_meta/software/metaGEM/qfiltered/sample1/sample1_R2.fastq.gz
    jobid: 1
    wildcards: IDs=sample1

/bin/sh: 1: sbatch: not found
Error submitting jobscript (exit code 127):

Job failed, going on with independent jobs.

Exiting because a job execution failed. Look above for error message
Complete log: /media/sf_stone_meta/software/metaGEM/.snakemake/log/2021-05-30T102512.578344.snakemake.log
#####################

**Comment by franciscozorrilla** [comment]
Hi Jint,

While metaGEM was designed and optimized for usage on high performance computer clusters, you can run it on a powerful computer or workstation by adding the `--local` flag to the `bash metaGEM.sh` command. Please refer to the following resources for more information and let me know if you have any further questions!

- Issue #44 
- Google colab [notebook](https://colab.research.google.com/drive/1I1S8AoGuJ9Oc2292vqAGTDmZcbnolbuj#scrollTo=7dqjNcjMrkK3), specifically sections 5 & 6 use the `--local` flag for running `metaGEM` on virutal machine

By the way, 40GB RAM is likely not enough to process real metagenomic datasets in a reasonable amount of time. I would suggest you use your institution's high performance computer cluster for running analysis with `metaGEM`.

**Comment by kingtom2016** [comment]
Thank you. Actually, I have done the sequence process (by others' clusters) like megahit which is resource-intensive computation. I would use the downstream analysis of metaGEM with my files. Thanks for your help!
