### ISSUE TITLE
feat: add drep for dereplicating MAGs across samples

### ISSUE THREAD

**Issue by franciscozorrilla** [franciscozorrilla/metaGEM#68]
Add rule to Snakefile for dereplicating MAGs:

```
dRep dereplicate output_directory -g path/to/genomes/*.fasta
```

[code](https://github.com/MrOlm/drep), [docs](https://drep.readthedocs.io/en/latest/index.html)

**Comment by jk00ANI** [comment]
Hi Francisco,
Thanks again for the great pipeline. Does metagem allows embaded dRep step? Or does it need to be performed independently after the bin reassembly step?
Thanks
Kunal

**Comment by franciscozorrilla** [comment]
Hey Kunal, glad that you are finding the workflow useful 🚀 
dRep is not currently implemented in the workflow, so you would have to do it on your own after reassembly.
Best wishes,
Francisco
