### ISSUE TITLE
No metabat/samplename/cov/*.all.depth file and an empty concoct coverage_table.tsv

### ISSUE THREAD

**Issue by slambrechts** [franciscozorrilla/metaGEM#82]
Hi Francisco,

For 4 out of 43 samples, the `/metabat/samplename/cov/*.all.depth` files are missing, the concoct `coverage_table.tsv` file is empty, but the `/maxbin/samplename/cov` folder does contain depth files. Does that mean `crossMap` did not yield sufficient information to yield bins for these samples?

This should not interfere with the remaining `metaGEM ` snakemake pipeline, right? Or should I remove these samples?

Kind regards,
Sam

**Comment by franciscozorrilla** [comment]
Hi Sam,

I assume you are referring to `crossMapSeries`, correct? I find it strange that it fails to produce an output for 2 out of 3 binners. Without having seen the log files, I suspect that most likely the jobs were terminated prematurely or failed for some reason. Can you access the log files for those jobs? I think they will be quite large, feel free to attach one or two of them in your post.

Indeed, I believe that not having those binner input files will end up causing problems with the `binRefine` rule (only for those failed samples), as it expects 3 different bin sets but you will only be providing one. You can proceed with the pipeline for the remaining samples.

Apologies for the late response, I was away at a conference without my laptop 🤓 
Best wishes,
Francisco
