### ISSUE TITLE
Regarding the generation of SMETANA's highly statistically significant difference for NGT/IGT/T2D

### ISSUE THREAD

**Issue by jckim012** [franciscozorrilla/metaGEM#84]
Hi Francisco,

Thank you for your metaGEM effort and sharing the pipeline. It's very useful for analyzing disease and patient specific metabolic networks.

I'm trying to reproduce the simulation results of your paper for the European women NGT/IGT/T2D data.

I'd like to analyze the details of SMETANA simulation result. So, I can analyze the patient specific metabolic networks, just like you already illustrated in the supplementary figures 11 - 14. In the current version of paper and/or code, I couldn't find out how I can generate these figures, i.e. highly statistically significant difference in metabolites, donors and receivers. If possible, could you share some code or method to generate these highly statistically significant difference data from SMETNA result?

I'am also very looking forward to seeing the update version your paper which will contains the detailed analysis for NGT/IGT/T2D data as you mentioned in previous issue.

Sincerely,

Jin

**Comment by LiZhihua1982** [comment]
hi， How to visualize the SMETANA simulation results from sample wgs_S2772Nr3. https://github.com/franciscozorrilla/unseenbio_metaGEM
![image](https://github.com/franciscozorrilla/metaGEM/assets/38903973/26afc45c-ae5f-4a3e-a49f-266268b159ff)

**Comment by LiZhihua1982** [comment]
Hi  I am sorry. Plot the box is simple using R
