### ISSUE TITLE
Question about applying method for different biomes

### ISSUE THREAD

**Issue by sskashaf** [franciscozorrilla/metaGEM#88]
Hi Francisco! 

Fantastic tool! Super excited to try it out. I am interested in applying your tool for the skin. A lot of the samples in your paper were from the gut. Do you know how I can best apply your tool to model interactions in the skin, which is more nutrient poor? Anything else (other than the media) that you can think of that would differ for the skin?

Many thanks,
Sara

**Comment by franciscozorrilla** [comment]
Hi Sara, happy to hear that you are interested in the pipeline! 💎 

Regarding media, this is something that you would have to adapt/design based on literature/domain knowledge and using metabolite IDs from the [bigg](http://bigg.ucsd.edu/) database. Besides that, I would perhaps expect that the communities are smaller than in the gut (i.e. less MAGs per sample). Unfortunately I have not studied the skin microbiome in detail so I am not sure what else would be unique to such an analysis, but you should be able to apply the metaGEM pipeline to those sample without any problems.

Please let me know if you come up with any further questions or interesting observations!

Best wishes,
Francisco
