### ISSUE TITLE
-h hours to allocated to job runtime

### ISSUE THREAD

**Issue by kunaljaani** [franciscozorrilla/metaGEM#99]
Hi Francisco,

I have query regarding the -h flag. I am running the bin reassembly and I had specified 24hrs but the job has not yet finished. Is there a way to resume the command from its last point?

bash metaGEM.sh -t binReassemble -c 28 -m 240 -h 24

Thank you
Kunal

**Comment by franciscozorrilla** [comment]
Hi Kunal, 

Looks like you probably figured it out. For that particular rule, I believe that metaWRAP does indeed have checkpointing, so re-submitting will simply resume where the last job left off. Did it work out for you?

Best wishes,
Francisco

**Comment by kunaljaani** [comment]
Hi Francisco,

Thank you for your reply. Ya, I could fix it with the suggested "--rerun-incomplet" flag from one of your earlier comments.

Thanks,
Kunal
